### PR TITLE
Remove requirement that website must be a "third party website"

### PR DESCRIPTION
**Pull request by timfromdigicert**

### CODE REVIEW

**Comment by DeanJC** [comment]
I'm still skeptical about removing this requirement. If I think back to why we put this in, we were getting applications from CAs that were only showing certs issued to their own websites. Hence, we had no proof that they were in the business of issuing public certs to 3rd parties. Some may argue that this has been overridden by Mozilla policies which check for this and if that's the case, then fine, we can remove.

**Comment by dzacharo** [comment]
> I'm still skeptical about removing this requirement. If I think back to why we put this in, we were getting applications from CAs that were only showing certs issued to their own websites. Hence, we had no proof that they were in the business of issuing public certs to 3rd parties. Some may argue that this has been overridden by Mozilla policies which check for this and if that's the case, then fine, we can remove.

Yes, that's the main argument. To accept a Certificate Issuer Member, we mainly focus on the audit and being accepted to a Member Certificate Consumer's Root store. A new publicly-trusted CA which is not trusted by many root stores can't "actively issue" nor provide certificates to third-parties because no one will want to get certificates that are not trusted by the majority of the WebPKI.

I hope this clarifies the intent.

**Comment by barrini** [comment]
I´m with Tim that this requirement does not add any value. We can have a CA that is audited and it´s on the different root stores and never issue a certificate, for whatever reasons (very unlikely but can happen) and similarly have a CA that wants to be added to the CABF and can´t make it because, as Dimitris says, none would want a certificate that is not trusted in any browser. So issuing a cert for a third-party site wouldn´t make you "better" in case you would like to be a CABF member.

**Comment by dzacharo** [comment]
This was addressed  by Ballot [Forum-19](https://github.com/cabforum/forum/pull/41)

**Pull request closed without merging**
